build:
  version: "3.0"

loans:
  message: "Welcome to EazyBank loans related local APIs"
  contactDetails:
    name: "Manick MR - Developer"
    email: "loans.local@eazybank.com"
  callSupport:
    - (555) 555-1444
    - (555) 523-2444
