spring:
  config:
    activate:
      on-profile: "prod"
build:
  version: "1.0"

cards:
  message: "Welcome to Loans related Prod APIs"
  contactDetails:
    name: "Prod owner - Prod"
    email: "loans.prod@eazybank.com"
  callSupport:
    - (111) 111-4444
    - (111) 111-4445